### ISSUE TITLE
Live site doesn't match content of this repo

### ISSUE THREAD

**Issue by SergeyMalkin** [RoelN/color-font-test#1]
In particular:

On live site: CBDT font only contains capital X, but site checks for lowercase x. 
In repo: specifically for CBDT font, you check for uppercase X.

Can you update site to make it work correctly again? It worked fine about a month ago. 

You can use Microsoft Edge on recent preview of Windows10, it supports all 4 formats :)

**Comment by RoelN** [comment]
Thanks for reporting! I'm actually deprecating this project in favor of [ChromaCheck](https://pixelambacht.nl/chromacheck/). It should report the same but uses cleaner test fonts. Would that work for you?

> You can use Microsoft Edge on recent preview of Windows10, it supports all 4 formats :)

That is _very exciting news_! I have a laptop with regular W10, can I check this there?

**Comment by SergeyMalkin** [comment]
Yes, ChromaCheck works. I just didn't know it is already online.

You will need recent preview build to try this. In case you can't, this is what ChromaCheck reports on latest Edge build:

Apple SBIX is supported
Microsoft COLR/CPAL is supported
Adobe and Mozilla SVG-in-OpenType is supported
Google CBDT/CBLC is supported

Thanks!
